namespace VolusionAccess.Services
{
	public class OrderColumnsBuilder
	{
		public static readonly string[] OrdersAllColumnsSet = new[]
		{
			OrderColumnsWithPrefix.OrderID,
			OrderColumnsWithPrefix.AccountNumber,
			OrderColumnsWithPrefix.AccountType,
			OrderColumnsWithPrefix.AddressValidated,
			OrderColumnsWithPrefix.Affiliate_Commissionable_Value,
			OrderColumnsWithPrefix.BankName,
			OrderColumnsWithPrefix.CustomerID,
			OrderColumnsWithPrefix.IsAGift,
			OrderColumnsWithPrefix.IsGTSOrder,
			OrderColumnsWithPrefix.Locked,
			OrderColumnsWithPrefix.Order_Entry_System,
			OrderColumnsWithPrefix.CancelDate,
			OrderColumnsWithPrefix.CancelReason,
			OrderColumnsWithPrefix.InitiallyShippedDate,
			OrderColumnsWithPrefix.LastModified,
			OrderColumnsWithPrefix.OrderDate,
			OrderColumnsWithPrefix.OrderDateUtc,
			OrderColumnsWithPrefix.OrderStatus,
			OrderColumnsWithPrefix.Order_Comments,
			OrderColumnsWithPrefix.PaymentAmount,
			OrderColumnsWithPrefix.PaymentDeclined,
			OrderColumnsWithPrefix.PaymentMethodID,
			OrderColumnsWithPrefix.Stock_Priority,
			OrderColumnsWithPrefix.Total_Payment_Authorized,
			OrderColumnsWithPrefix.Total_Payment_Received,
			OrderColumnsWithPrefix.TotalShippingCost,
			OrderColumnsWithPrefix.SalesTax1,
			OrderColumnsWithPrefix.SalesTax2,
			OrderColumnsWithPrefix.SalesTax3,
			OrderColumnsWithPrefix.SalesTaxRate,
			OrderColumnsWithPrefix.SalesTaxRate1,
			OrderColumnsWithPrefix.SalesTaxRate2,
			OrderColumnsWithPrefix.SalesTaxRate3,
			OrderColumnsWithPrefix.BillingAddress1,
			OrderColumnsWithPrefix.BillingAddress2,
			OrderColumnsWithPrefix.BillingCity,
			OrderColumnsWithPrefix.BillingCompanyName,
			OrderColumnsWithPrefix.BillingCountry,
			OrderColumnsWithPrefix.BillingFaxNumber,
			OrderColumnsWithPrefix.BillingFirstName,
			OrderColumnsWithPrefix.BillingLastName,
			OrderColumnsWithPrefix.BillingPhoneNumber,
			OrderColumnsWithPrefix.BillingPostalCode,
			OrderColumnsWithPrefix.BillingState,
			OrderColumnsWithPrefix.ShipAddress1,
			OrderColumnsWithPrefix.ShipAddress2,
			OrderColumnsWithPrefix.ShipCity,
			OrderColumnsWithPrefix.ShipCompanyName,
			OrderColumnsWithPrefix.ShipCountry,
			OrderColumnsWithPrefix.ShipDate,
			OrderColumnsWithPrefix.ShipFaxNumber,
			OrderColumnsWithPrefix.ShipFirstName,
			OrderColumnsWithPrefix.ShipLastName,
			OrderColumnsWithPrefix.Shipped,
			OrderColumnsWithPrefix.ShipPhoneNumber,
			OrderColumnsWithPrefix.Shipping_Locked,
			OrderColumnsWithPrefix.ShippingMethodID,
			OrderColumnsWithPrefix.ShipPostalCode,
			OrderColumnsWithPrefix.ShipResidential,
			OrderColumnsWithPrefix.ShipState,
			OrderColumnsWithPrefix.OrderDetails,
		};

		public static readonly string[] OrdersMinimalColumnsSet = new[]
		{
			OrderColumnsWithPrefix.OrderID,
			// we are sure it is not used //OrderColumnsWithPrefix.AccountNumber,
			// we are sure it is not used //OrderColumnsWithPrefix.AccountType,
			// we are sure it is not used //OrderColumnsWithPrefix.AddressValidated,
			// we are sure it is not used //OrderColumnsWithPrefix.Affiliate_Commissionable_Value,
			// we are sure it is not used //OrderColumnsWithPrefix.BankName,
			// we are sure it is not used //OrderColumnsWithPrefix.CustomerID,
			// we are sure it is not used //OrderColumnsWithPrefix.IsAGift,
			// we are sure it is not used //OrderColumnsWithPrefix.IsGTSOrder,
			// we are sure it is not used //OrderColumnsWithPrefix.Locked,
			// we are sure it is not used //OrderColumnsWithPrefix.Order_Entry_System,

			OrderColumnsWithPrefix.CancelDate,
			// we are sure it is not used //OrderColumnsWithPrefix.CancelReason,
			OrderColumnsWithPrefix.InitiallyShippedDate,
			OrderColumnsWithPrefix.LastModified,
			OrderColumnsWithPrefix.OrderDate,
			OrderColumnsWithPrefix.OrderDateUtc,
			OrderColumnsWithPrefix.OrderStatus,
			OrderColumnsWithPrefix.Order_Comments,
			OrderColumnsWithPrefix.PaymentAmount,
			// we are sure it is not used //OrderColumnsWithPrefix.PaymentDeclined,
			// we are sure it is not used //OrderColumnsWithPrefix.PaymentMethodID,
			// we are sure it is not used //OrderColumnsWithPrefix.Stock_Priority,
			// we are sure it is not used //OrderColumnsWithPrefix.Total_Payment_Authorized,
			// we are sure it is not used //OrderColumnsWithPrefix.Total_Payment_Received,
			// we are sure it is not used //OrderColumnsWithPrefix.TotalShippingCost,
			// we are sure it is not used //OrderColumnsWithPrefix.SalesTax1,
			// we are sure it is not used //OrderColumnsWithPrefix.SalesTax2,
			// we are sure it is not used //OrderColumnsWithPrefix.SalesTax3,
			// we are sure it is not used //OrderColumnsWithPrefix.SalesTaxRate,
			// we are sure it is not used //OrderColumnsWithPrefix.SalesTaxRate1,
			// we are sure it is not used //OrderColumnsWithPrefix.SalesTaxRate2,
			// we are sure it is not used //OrderColumnsWithPrefix.SalesTaxRate3,
			// we are sure it is not used //OrderColumnsWithPrefix.BillingAddress1,
			// we are sure it is not used //OrderColumnsWithPrefix.BillingAddress2,
			// we are sure it is not used //OrderColumnsWithPrefix.BillingCity,
			OrderColumnsWithPrefix.BillingCompanyName,
			// we are sure it is not used //OrderColumnsWithPrefix.BillingCountry,
			// we are sure it is not used //OrderColumnsWithPrefix.BillingFaxNumber,
			OrderColumnsWithPrefix.BillingFirstName,
			OrderColumnsWithPrefix.BillingLastName,
			OrderColumnsWithPrefix.BillingPhoneNumber,
			// we are sure it is not used //OrderColumnsWithPrefix.BillingPostalCode,
			// we are sure it is not used //OrderColumnsWithPrefix.BillingState,
			OrderColumnsWithPrefix.ShipAddress1,
			OrderColumnsWithPrefix.ShipAddress2,
			OrderColumnsWithPrefix.ShipCity,
			// we are sure it is not used //OrderColumnsWithPrefix.ShipCompanyName,
			OrderColumnsWithPrefix.ShipCountry,
			//OrderColumnsWithPrefix.ShipDate,
			// we are sure it is not used //OrderColumnsWithPrefix.ShipFaxNumber,
			// we are sure it is not used //OrderColumnsWithPrefix.ShipFirstName,
			// we are sure it is not used //OrderColumnsWithPrefix.ShipLastName,
			OrderColumnsWithPrefix.Shipped,
			// we are sure it is not used //OrderColumnsWithPrefix.ShipPhoneNumber,
			// we are sure it is not used //OrderColumnsWithPrefix.Shipping_Locked,
			OrderColumnsWithPrefix.ShippingMethodID,
			OrderColumnsWithPrefix.ShipPostalCode,
			// we are sure it is not used //OrderColumnsWithPrefix.ShipResidential,
			OrderColumnsWithPrefix.ShipState,
			OrderColumnsWithPrefix.OrderDetails,
		};
	}
}