namespace VolusionAccess.Services
{
	public class OrderColumnsBuilder
	{
		public static readonly string[] OrdersAllColumnsSet = new[]
		{
			OrderColumnsNamesWithPrefix.OrderID,
			OrderColumnsNamesWithPrefix.AccountNumber,
			OrderColumnsNamesWithPrefix.AccountType,
			OrderColumnsNamesWithPrefix.AddressValidated,
			OrderColumnsNamesWithPrefix.Affiliate_Commissionable_Value,
			OrderColumnsNamesWithPrefix.BankName,
			OrderColumnsNamesWithPrefix.CustomerID,
			OrderColumnsNamesWithPrefix.IsAGift,
			OrderColumnsNamesWithPrefix.IsGTSOrder,
			OrderColumnsNamesWithPrefix.Locked,
			OrderColumnsNamesWithPrefix.Order_Entry_System,
			OrderColumnsNamesWithPrefix.CancelDate,
			OrderColumnsNamesWithPrefix.CancelReason,
			OrderColumnsNamesWithPrefix.InitiallyShippedDate,
			OrderColumnsNamesWithPrefix.LastModified,
			OrderColumnsNamesWithPrefix.OrderDate,
			OrderColumnsNamesWithPrefix.OrderDateUtc,
			OrderColumnsNamesWithPrefix.OrderStatus,
			OrderColumnsNamesWithPrefix.Order_Comments,
			OrderColumnsNamesWithPrefix.PaymentAmount,
			OrderColumnsNamesWithPrefix.PaymentDeclined,
			OrderColumnsNamesWithPrefix.PaymentMethodID,
			OrderColumnsNamesWithPrefix.Stock_Priority,
			OrderColumnsNamesWithPrefix.Total_Payment_Authorized,
			OrderColumnsNamesWithPrefix.Total_Payment_Received,
			OrderColumnsNamesWithPrefix.TotalShippingCost,
			OrderColumnsNamesWithPrefix.SalesTax1,
			OrderColumnsNamesWithPrefix.SalesTax2,
			OrderColumnsNamesWithPrefix.SalesTax3,
			OrderColumnsNamesWithPrefix.SalesTaxRate,
			OrderColumnsNamesWithPrefix.SalesTaxRate1,
			OrderColumnsNamesWithPrefix.SalesTaxRate2,
			OrderColumnsNamesWithPrefix.SalesTaxRate3,
			OrderColumnsNamesWithPrefix.BillingAddress1,
			OrderColumnsNamesWithPrefix.BillingAddress2,
			OrderColumnsNamesWithPrefix.BillingCity,
			OrderColumnsNamesWithPrefix.BillingCompanyName,
			OrderColumnsNamesWithPrefix.BillingCountry,
			OrderColumnsNamesWithPrefix.BillingFaxNumber,
			OrderColumnsNamesWithPrefix.BillingFirstName,
			OrderColumnsNamesWithPrefix.BillingLastName,
			OrderColumnsNamesWithPrefix.BillingPhoneNumber,
			OrderColumnsNamesWithPrefix.BillingPostalCode,
			OrderColumnsNamesWithPrefix.BillingState,
			OrderColumnsNamesWithPrefix.ShipAddress1,
			OrderColumnsNamesWithPrefix.ShipAddress2,
			OrderColumnsNamesWithPrefix.ShipCity,
			OrderColumnsNamesWithPrefix.ShipCompanyName,
			OrderColumnsNamesWithPrefix.ShipCountry,
			OrderColumnsNamesWithPrefix.ShipDate,
			OrderColumnsNamesWithPrefix.ShipFaxNumber,
			OrderColumnsNamesWithPrefix.ShipFirstName,
			OrderColumnsNamesWithPrefix.ShipLastName,
			OrderColumnsNamesWithPrefix.Shipped,
			OrderColumnsNamesWithPrefix.ShipPhoneNumber,
			OrderColumnsNamesWithPrefix.Shipping_Locked,
			OrderColumnsNamesWithPrefix.ShippingMethodID,
			OrderColumnsNamesWithPrefix.ShipPostalCode,
			OrderColumnsNamesWithPrefix.ShipResidential,
			OrderColumnsNamesWithPrefix.ShipState,
			OrderColumnsNamesWithPrefix.OrderDetails,
		};

		public static readonly string[] OrdersMinimalColumnsSet = new[]
		{
			OrderColumnsNamesWithPrefix.OrderID,
			// we are sure it is not used //OrderColumnsWithPrefix.AccountNumber,
			// we are sure it is not used //OrderColumnsWithPrefix.AccountType,
			// we are sure it is not used //OrderColumnsWithPrefix.AddressValidated,
			// we are sure it is not used //OrderColumnsWithPrefix.Affiliate_Commissionable_Value,
			// we are sure it is not used //OrderColumnsWithPrefix.BankName,
			// we are sure it is not used //OrderColumnsWithPrefix.CustomerID,
			// we are sure it is not used //OrderColumnsWithPrefix.IsAGift,
			// we are sure it is not used //OrderColumnsWithPrefix.IsGTSOrder,
			// we are sure it is not used //OrderColumnsWithPrefix.Locked,
			// we are sure it is not used //OrderColumnsWithPrefix.Order_Entry_System,

			OrderColumnsNamesWithPrefix.CancelDate,
			// we are sure it is not used //OrderColumnsWithPrefix.CancelReason,
			OrderColumnsNamesWithPrefix.InitiallyShippedDate,
			OrderColumnsNamesWithPrefix.LastModified,
			OrderColumnsNamesWithPrefix.OrderDate,
			OrderColumnsNamesWithPrefix.OrderDateUtc,
			OrderColumnsNamesWithPrefix.OrderStatus,
			OrderColumnsNamesWithPrefix.Order_Comments,
			OrderColumnsNamesWithPrefix.PaymentAmount,
			// we are sure it is not used //OrderColumnsWithPrefix.PaymentDeclined,
			// we are sure it is not used //OrderColumnsWithPrefix.PaymentMethodID,
			// we are sure it is not used //OrderColumnsWithPrefix.Stock_Priority,
			// we are sure it is not used //OrderColumnsWithPrefix.Total_Payment_Authorized,
			// we are sure it is not used //OrderColumnsWithPrefix.Total_Payment_Received,
			// we are sure it is not used //OrderColumnsWithPrefix.TotalShippingCost,
			// we are sure it is not used //OrderColumnsWithPrefix.SalesTax1,
			// we are sure it is not used //OrderColumnsWithPrefix.SalesTax2,
			// we are sure it is not used //OrderColumnsWithPrefix.SalesTax3,
			// we are sure it is not used //OrderColumnsWithPrefix.SalesTaxRate,
			// we are sure it is not used //OrderColumnsWithPrefix.SalesTaxRate1,
			// we are sure it is not used //OrderColumnsWithPrefix.SalesTaxRate2,
			// we are sure it is not used //OrderColumnsWithPrefix.SalesTaxRate3,
			// we are sure it is not used //OrderColumnsWithPrefix.BillingAddress1,
			// we are sure it is not used //OrderColumnsWithPrefix.BillingAddress2,
			// we are sure it is not used //OrderColumnsWithPrefix.BillingCity,
			OrderColumnsNamesWithPrefix.BillingCompanyName,
			// we are sure it is not used //OrderColumnsWithPrefix.BillingCountry,
			// we are sure it is not used //OrderColumnsWithPrefix.BillingFaxNumber,
			OrderColumnsNamesWithPrefix.BillingFirstName,
			OrderColumnsNamesWithPrefix.BillingLastName,
			OrderColumnsNamesWithPrefix.BillingPhoneNumber,
			// we are sure it is not used //OrderColumnsWithPrefix.BillingPostalCode,
			// we are sure it is not used //OrderColumnsWithPrefix.BillingState,
			OrderColumnsNamesWithPrefix.ShipAddress1,
			OrderColumnsNamesWithPrefix.ShipAddress2,
			OrderColumnsNamesWithPrefix.ShipCity,
			// we are sure it is not used //OrderColumnsWithPrefix.ShipCompanyName,
			OrderColumnsNamesWithPrefix.ShipCountry,
			//OrderColumnsWithPrefix.ShipDate,
			// we are sure it is not used //OrderColumnsWithPrefix.ShipFaxNumber,
			// we are sure it is not used //OrderColumnsWithPrefix.ShipFirstName,
			// we are sure it is not used //OrderColumnsWithPrefix.ShipLastName,
			OrderColumnsNamesWithPrefix.Shipped,
			// we are sure it is not used //OrderColumnsWithPrefix.ShipPhoneNumber,
			// we are sure it is not used //OrderColumnsWithPrefix.Shipping_Locked,
			OrderColumnsNamesWithPrefix.ShippingMethodID,
			OrderColumnsNamesWithPrefix.ShipPostalCode,
			// we are sure it is not used //OrderColumnsWithPrefix.ShipResidential,
			OrderColumnsNamesWithPrefix.ShipState,
			OrderColumnsNamesWithPrefix.OrderDetails,
		};
	}
}